# Generated by Django 5.0.6 on 2024-07-03 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('age', models.IntegerField()),
                ('currentSmoker', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('cigsPerDay', models.IntegerField(blank=True, null=True)),
                ('BPmeds', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('prevalentStroke', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('prevalentHyp', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('diabetes', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('totChol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sysBP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diaBP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heartRate', models.IntegerField()),
                ('glucose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_health_records',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
