# Generated by Django 5.0.6 on 2024-07-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prevalentHypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prevalentStroke',
            field=models.BooleanField(default=False),
        ),
    ]
