# Generated by Django 5.0.6 on 2024-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_nutritionalintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minerals', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
