# Generated by Django 5.0.6 on 2024-07-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_diabetes_user_dob_user_prevalenthypertension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentSmoker',
            field=models.BooleanField(default=False),
        ),
    ]
