# Generated by Django 5.0.6 on 2024-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_currentsmoker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currentSmoker',
        ),
        migrations.AddField(
            model_name='user',
            name='isHealthy',
            field=models.BooleanField(default=True),
        ),
    ]
