# Generated by Django 5.0.6 on 2024-07-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_drink',
            field=models.BooleanField(default=False),
        ),
    ]
