# Generated by Django 5.0.6 on 2024-07-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_food_is_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalintake',
            name='quantity',
            field=models.CharField(default='100 grams', max_length=255),
        ),
    ]
