### Signup a new user
POST http://127.0.0.1:8000/user/signup/
Content-Type: application/json

{
  "email": "mash@yopmail.com",
  "password": "testpassword123",
  "username": "mash",
  "age": 25,
  "gender": "male",
  "height": 175.5,
  "weight": 70.0,
  "dob": "1999-01-15",
  "prevalentStroke": false,
  "prevalentHypertension": false,
  "diabetes": false,
  "currentSmoker": false
}

### Login into account
POST http://127.0.0.1:8000/user/login/
Content-Type: application/json

{
    "email" : "mash@yopmail.com",
    "password": "testpassword123"
}
### Confirm Email
POST http://127.0.0.1:8000/user/confirm-email/
Content-Type: application/json

{
  "confirmation_code": "fFBfYC"
}


# 38e1321a8201a17cd6aef90ac90da7c58d39f77a

### add nutrient intake
POST http://127.0.0.1:8000/user/intake/add/
Content-Type: application/json
Authorization: Token 38e1321a8201a17cd6aef90ac90da7c58d39f77a

{
  "food_item": "Mango",
  "quantity": 100,
  "is_drink": false
}

### Check user login
GET http://127.0.0.1:8000/user/is-user-login
Authorization: Token 38e1321a8201a17cd6aef90ac90da7c58d39f77a


### Get food intake summary
POST http://127.0.0.1:8000/user/intake/summary/
Content-Type: application/json
Authorization: Token 38e1321a8201a17cd6aef90ac90da7c58d39f77a

{
  "start_date": "2024-07-05",
  "end_date": "2024-07-05"
}