### Signup a new user
POST http://127.0.0.1:8000/user/signup/
Content-Type: application/json

{
  "email": "sam123@yopmail.com",
  "password": "testpassword123",
  "username": "sam123",
  "age": 25,
  "gender": "male",
  "height": 175.5,
  "weight": 70.0,
  "dob": "1999-01-15",
  "prevalentStroke": false,
  "prevalentHypertension": false,
  "diabetes": false,
  "currentSmoker": false
}

### Login into account
POST http://127.0.0.1:8000/user/login/
Content-Type: application/json

{
    "email" : "mashhoodzaidi123@yopmail.com",
    "password": "testpassword123"
}
### Confirm Email
POST http://127.0.0.1:8000/user/confirm-email/
Content-Type: application/json

{
  "confirmation_code": "D89p35"
}


# 31b5888b29cceae3c55eece878037b12d31ca5f1